
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CT_HOADON](
	[MAHD] [varchar](10) NOT NULL,
	[MAP] [varchar](5) NOT NULL,
	[NGAYDI] [datetime] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[MAHD] ASC,
	[MAP] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[HOADON](
	[MAHD] [varchar](10) NOT NULL,
	[NGAYTHANHTOAN] [datetime] NOT NULL,
	[SOTIEN] [int] NULL,
	[MANV] [varchar](5) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[MAHD] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[KHACHHANG](
	[MAKH] [varchar](5) NOT NULL,
	[TENKH] [nvarchar](30) NOT NULL,
	[DIACHI] [nvarchar](50) NULL,
	[GIOITINH] [nvarchar](5) NULL,
	[CMND] [varchar](14) NULL,
	[SDT] [char](13) NULL,
PRIMARY KEY CLUSTERED 
(
	[MAKH] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[NHANVIEN](
	[MANV] [varchar](5) NOT NULL,
	[TENNV] [nvarchar](30) NOT NULL,
	[GIOITINH] [nvarchar](5) NULL,
	[NGAYSINH] [smalldatetime] NOT NULL,
	[DIACHI] [nvarchar](50) NULL,
	[SDT] [char](15) NULL,
PRIMARY KEY CLUSTERED 
(
	[MANV] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PHIEUDANGKY](
	[MAPDK] [varchar](15) NOT NULL,
	[MAKH] [varchar](5) NOT NULL,
	[MANV] [varchar](5) NOT NULL,
	[MAHD] [varchar](10) NOT NULL,
	[NGAYO] [datetime] NOT NULL,
	[MAP] [varchar](5) NOT NULL,
	[TRATRUOC] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[MAPDK] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PHONG](
	[MAP] [varchar](5) NOT NULL,
	[LOAIPHONG] [nvarchar](10) NOT NULL,
	[TINHTRANG] [nvarchar](20) NOT NULL,
	[GIAPHONG] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[MAP] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[PHONG] ADD  DEFAULT ((0)) FOR [GIAPHONG]
GO
ALTER TABLE [dbo].[CT_HOADON]  WITH CHECK ADD  CONSTRAINT [fk_CT_HOADON_HOADON] FOREIGN KEY([MAHD])
REFERENCES [dbo].[HOADON] ([MAHD])
GO
ALTER TABLE [dbo].[CT_HOADON] CHECK CONSTRAINT [fk_CT_HOADON_HOADON]
GO
ALTER TABLE [dbo].[CT_HOADON]  WITH CHECK ADD  CONSTRAINT [fk_CT_HOADON_PHONG] FOREIGN KEY([MAP])
REFERENCES [dbo].[PHONG] ([MAP])
GO
ALTER TABLE [dbo].[CT_HOADON] CHECK CONSTRAINT [fk_CT_HOADON_PHONG]
GO
ALTER TABLE [dbo].[HOADON]  WITH CHECK ADD  CONSTRAINT [fk_HOADON_NHANVIEN] FOREIGN KEY([MANV])
REFERENCES [dbo].[NHANVIEN] ([MANV])
GO
ALTER TABLE [dbo].[HOADON] CHECK CONSTRAINT [fk_HOADON_NHANVIEN]
GO
ALTER TABLE [dbo].[PHIEUDANGKY]  WITH CHECK ADD  CONSTRAINT [fk_PHIEUDANGKY_HOADON] FOREIGN KEY([MAHD])
REFERENCES [dbo].[HOADON] ([MAHD])
GO
ALTER TABLE [dbo].[PHIEUDANGKY] CHECK CONSTRAINT [fk_PHIEUDANGKY_HOADON]
GO
ALTER TABLE [dbo].[PHIEUDANGKY]  WITH CHECK ADD  CONSTRAINT [fk_PHIEUDANGKY_KHACHHANG] FOREIGN KEY([MAKH])
REFERENCES [dbo].[KHACHHANG] ([MAKH])
GO
ALTER TABLE [dbo].[PHIEUDANGKY] CHECK CONSTRAINT [fk_PHIEUDANGKY_KHACHHANG]
GO
ALTER TABLE [dbo].[PHIEUDANGKY]  WITH CHECK ADD  CONSTRAINT [fk_PHIEUDANGKY_NHANVIEN] FOREIGN KEY([MANV])
REFERENCES [dbo].[NHANVIEN] ([MANV])
GO
ALTER TABLE [dbo].[PHIEUDANGKY] CHECK CONSTRAINT [fk_PHIEUDANGKY_NHANVIEN]
GO
ALTER TABLE [dbo].[PHIEUDANGKY]  WITH CHECK ADD  CONSTRAINT [fk_PHIEUDANGKY_PHONG] FOREIGN KEY([MAP])
REFERENCES [dbo].[PHONG] ([MAP])
GO
ALTER TABLE [dbo].[PHIEUDANGKY] CHECK CONSTRAINT [fk_PHIEUDANGKY_PHONG]
GO
